name: 🧪 Test building with BuildKit (Daemonless)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: moby/buildkit:rootless
      options: >-
        --user root
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
    
    steps:
      - name: Build and push
        shell: sh
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: trucpd/kubernoodles/kaniko-build:test
          # THÊM CÁC FLAG NÀY:
          # Ép BuildKit chạy mode rootless dù container là root
          # Và tắt sandbox để chạy được trong container khác
          BUILDKITD_FLAGS: "--rootless --oci-worker-no-process-sandbox"
        run: |
          # 1. Setup Auth vào /tmp
          export DOCKER_CONFIG="/tmp/.docker"
          mkdir -p $DOCKER_CONFIG
          AUTH=$(echo -n "trucpd:${{ secrets.GITHUB_TOKEN }}" | base64)
          echo "{\"auths\": {\"$REGISTRY\": {\"auth\": \"$AUTH\"}}}" > $DOCKER_CONFIG/config.json

          # 2. Khởi tạo các thư mục cần thiết mà rootlesskit yêu cầu
          mkdir -p /run/user/1000
          export XDG_RUNTIME_DIR=/run/user/1000

          # 3. Chạy buildctl
          buildctl-daemonless.sh build \
            --frontend dockerfile.v0 \
            --local context=https://github.com/trucpd/kubernoodles.git#refs/heads/main \
            --local dockerfile=./images/kaniko-build-test.Dockerfile \
            --output type=image,name=$REGISTRY/$IMAGE_NAME,push=true
